### ISSUE TITLE
Publish to official Atom.io repository

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-lsp-client-atom#6]
or an unofficial if too complicated/long?

also update readme with information to install it then

**Comment by apupier** [comment]
https://flight-manual.atom.io/hacking-atom/sections/publishing/

**Comment by apupier** [comment]
published on https://atom.io/packages/camel-lsp-client-atom

**Comment by djelinek** [comment]
closing - verified on https://atom.io/packages/camel-lsp-client-atom
